# Generated by Django 5.2.4 on 2025-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_type',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('kakao', 'Kakao')], max_length=20, null=True),
        ),
    ]
