# Generated by Django 5.2.4 on 2025-07-17 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField(default=0)),
                ('defender_card', models.IntegerField(blank=True, null=True)),
                ('winning_condition', models.CharField(choices=[('high', 'High wins'), ('low', 'Low wins')], default='high', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('attacker', 'Attacker Wins'), ('defender', 'Defender Wins'), ('draw', 'Draw')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_started', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
